const express = require('express')
const adminRoute = express()

const adminController = require('../controllers/adminController')
const auth = require('../middleware/adminAuth')

adminRoute.get('/', auth.isLogout, adminController.loadAdminLogin)
adminRoute.post('/', adminController.loginValidate)
adminRoute.get('/home', adminController.loadDashboard)
adminRoute.get('/usermanage', adminController.loadUserManagement)
adminRoute.get('/logout', auth.isLogout, adminController.adminLogout)
adminRoute.get('/blockuser/:id', adminController.blockUser)
adminRoute.get('/unblockuser/:id', adminController.unBlockUser)
adminRoute.get('/categorymanage', adminController.loadCategory)
adminRoute.get('/addcategory', adminController.loadAddCategory)
adminRoute.post('/addcategory', adminController.AddCategory)
adminRoute.get('/editcategory', adminController.loadEditcategory)
adminRoute.post('/editcategory', adminController.editCategory)
adminRoute.get('/deletecategory', adminController.deleteCategory)
adminRoute.get('/productmanage', adminController.loadProductManage)
adminRoute.get('/addproduct', adminController.loadAddProductPage)
adminRoute.post('/addproduct', adminController.addProduct)
adminRoute.get('/editproduct', adminController.loadEditProductPage)
adminRoute.get('/deleteproduct', adminController.deleteProduct)
adminRoute.post('/editproduct', adminController.editProduct)
adminRoute.get('/orderManage', adminController.loadOrderManagePage)
adminRoute.get('/invoice', adminController.getInvoice)
adminRoute.get('/bannerManage', adminController.laodBannerManage)
adminRoute.get('/couponManage', adminController.laodCouponManage)
adminRoute.get('/addCoupon', adminController.loadaddCoupon)
adminRoute.get('/editCoupon', adminController.loadEditCoupon)
adminRoute.get('/deleteCoupon', adminController.deleteCoupon)
adminRoute.get('/bannerManage', adminController.loadBannerManage)
adminRoute.get('/addBanner', adminController.loadAddBanner)
adminRoute.get('/deleteBanner', adminController.deleteBanner)
adminRoute.get('/dailySales', adminController.loadDailySales)
adminRoute.get('/weeklySales', adminController.loadWeeklySales)
adminRoute.get('/yearlySales', adminController.loadYearlySales)
adminRoute.post('/addBanner', adminController.addBanner)
adminRoute.post('/editCoupon', adminController.editCoupon)
adminRoute.post('/addCoupon', adminController.addCoupon)

adminRoute.post('/orderStatus', adminController.changeOrderStatus)
adminRoute.post('/cancelOrder', adminController.cancelOrder)


adminRoute.get('*', function (req, res) {
  res.redirect('/admin')
})

module.exports = adminRoute
